#POC 2 yml 
name: add script to workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: using variable
        run : echo"used repo level variable{${{ vars.REPOVAR }}"
      - name: Print Working Directory
        run: |
          pwd
          ls -l
      - name: Adding Script to my workflow in github actions
        run: |
          # bash /home/runner/work/gitHub_actions_POC2/gitHub_actions_POC2/
          bash ./script.sh
